Repository nextcloud/user_migration, pull requests merged in 2022-10, with the labels that each got.

#264 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#265 composer run cs:fix
  lib/Migration/Version00001Date20220411114609.php
  lib/Migration/Version00001Date20220412116131.php
  lib/Settings/Personal/Section.php
  lib/Settings/Personal/Settings.php
Labels: 3. to review

#266 Add configuration for transifex
  .l10nignore
  .tx/config
  l10n/.gitkeep
Labels: 4. to release, backport-request

#270 Improve README
  README.md
Labels: 4. to release, backport-request

#283 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#288 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#277 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#285 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#282 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#281 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#280 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#279 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#278 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#284 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#286 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#290 v2.0.0
  appinfo/info.xml
Labels: 4. to release

#293 v2.0.1
  appinfo/info.xml
Labels: 4. to release

#295 Fix outdated app store description
  appinfo/info.xml
Labels: 3. to review, backport-request, documentation

#297 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#304 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
