Repository nextcloud/user_migration, pull requests merged in 2022-08, with the labels that each got.

#212 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#213 Add workflow to update christophwurst/nextcloud dependency nightly
  .github/workflows/update-christophwurst-nextcloud.yml
Labels: 3. to review, dependencies

#217 Update npm and node engines versions
  package.json
Labels: 4. to release, dependencies

#214 [stable24] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 4. to release, dependencies

#234 Bump psalm level from 5 to 4 (lower is stricter)
  lib/Command/Export.php
  psalm.xml
Labels: 4. to release

#207 Bump dev version on main
  appinfo/info.xml
Labels: 4. to release
