Repository nextcloud/user_migration, pull requests merged in 2022-05, with the labels that each got.

#139 [stable24] Add job cancellation
  appinfo/routes.php
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/Controller/ApiController.php
  lib/Service/UserMigrationService.php
  package-lock.json
  package.json
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/services/migrationService.js
  src/shared/constants.js
  src/views/Personal/Settings.vue
Labels: 3. to review

#140 v1.0.1
  appinfo/info.xml
Labels: 4. to release

#142 Add screenshots and extended description
  .nextcloudignore
  README.md
  appinfo/info.xml
  screenshots/export.png
  screenshots/exporting.png
  screenshots/import.png
Labels: 4. to release, backport-request

#145 Update description and formatting
  README.md
  appinfo/info.xml
Labels: 3. to review, backport-request

#146 Support Nextcloud 24 on main
  appinfo/info.xml
Labels: 3. to review

#147 v1.0.3
  appinfo/info.xml
Labels: 3. to review

#155 Fix Undefined variable $importJob error
  lib/Service/UserMigrationService.php
Labels: 3. to review, backport-request

#157 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#154 Switch to standard phpunit workflows
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
Labels: 3. to review, backport-request

#160 v1.0.4
  appinfo/info.xml
Labels: 4. to release

#159 [stable24] Switch to standard phpunit workflows
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
Labels: 3. to review

#164 Fix crashes when files_versions is disabled
  lib/BackgroundJob/UserExportJob.php
  lib/BackgroundJob/UserImportJob.php
  lib/Migrator/FilesMigrator.php
Labels: 2. developing

#167 Add selective data export to CLI
  lib/Command/Export.php
Labels: 4. to release, backport-request, enhancement
