Repository nextcloud/user_migration, pull requests merged in 2022-06, with the labels that each got.

#168 Augment stdout of import command
  lib/Command/Export.php
  lib/Command/Import.php
Labels: 3. to review, backport-request, enhancement

#136 Show estimated export size and display exportability warnings
  js/user_migration-admin-settings.js
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/Controller/ApiController.php
  lib/Service/UserMigrationService.php
  src/admin-settings.js
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/personal-settings.js
  src/services/migrationService.js
  src/shared/logger.js
  src/shared/utils.js
  src/views/Personal/Settings.vue
Labels: 4. to release, backport-request, enhancement

#176 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#177 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#174 [stable24] Show estimated export size and display exportability warnings
  js/user_migration-admin-settings.js
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/Controller/ApiController.php
  lib/Service/UserMigrationService.php
  src/admin-settings.js
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/personal-settings.js
  src/services/migrationService.js
  src/shared/logger.js
  src/shared/utils.js
  src/views/Personal/Settings.vue
Labels: 4. to release, enhancement
