Repository nextcloud/user_migration, pull requests merged in 2022-03, with the labels that each got.

#49 Do not export home path, it may be sensitive server information and i…
  lib/Service/UserMigrationService.php
Labels: 3. to review

#46 Drop account export and import
  lib/Service/UserMigrationService.php
Labels: 3. to review, enhancement

#52 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#53 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#54 Allow importing over an existing user
  lib/Command/Import.php
  lib/Service/UserMigrationService.php
Labels: 3. to review

#57 Adapt code to new interface methods and use them
  lib/Exception/UserMigrationException.php
  lib/ImportSource.php
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
Labels: 3. to review

#58 Add easier to compare sql extracts to test script
  tests/scripts/test_user_migration.sh
Labels: 3. to review

#59 Overwrite any existing data when importing in an existing user
  lib/ImportSource.php
Labels: 3. to review

#48 Export and import files comments
  lib/Migrator/FilesMigrator.php
Labels: 3. to review
