Repository nextcloud/user_migration, pull requests merged in 2022-02, with the labels that each got.

#35 Add test script
  tests/scripts/test_user_migration.sh
Labels: 4. to release

#38 Make test script portable
  tests/scripts/test_user_migration.sh
Labels: 3. to review, enhancement, integration

#27 Migration orchestration
  composer.json
  composer.lock
  lib/ExportDestination.php
  lib/IExportDestination.php
  lib/IImportSource.php
  lib/ImportSource.php
  lib/Service/UserMigrationService.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/stub.phpstub
Labels: 3. to review

#40 Add Dependabot reviewers
  .github/dependabot.yml
Labels: 3. to review

#41 List the files of a folder
  lib/ImportSource.php
Labels: 3. to review, enhancement

#45 Minor changes for code readability
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
Labels: 3. to review
