Repository nextcloud/user_migration, pull requests merged in 2022-11, with the labels that each got.

#305 [stable24] Update workflows from nextcloud/.github
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: 3. to review

#303 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#306 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#314 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies
