Repository nextcloud/user_migration, pull requests merged in 2022-09, with the labels that each got.

#244 Adjust testing matrix for Nextcloud 25 on stable25
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-christophwurst-nextcloud.yml
Labels: 4. to release

#241 Ignore shares in FilesMigrator
  lib/Db/UserExport.php
  lib/Db/UserImport.php
  lib/ExportDestination.php
  lib/Migrator/FilesMigrator.php
Labels: 3. to review

#252 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies
