Repository nextcloud/user_migration, pull requests merged in 2022-04, with the labels that each got.

#73 Update main php testing versions
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
Labels: 3. to review

#78 Revert removal of background job
  appinfo/info.xml
  lib/BackgroundJob/UserExportJob.php
  lib/Db/UserExport.php
  lib/Db/UserExportMapper.php
Labels: 3. to review

#76 Extend files migrator
  lib/Migrator/FilesMigrator.php
Labels: 3. to review

#80 Use migrators id string instead of class name
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
Labels: 3. to review

#87 Fix argument name for UserExport setter
  lib/Db/UserExport.php
Labels: 3. to review

#89 Avoid calling getPath on IExportDestination, it only makes sense with…
  lib/Command/Export.php
  lib/Service/UserMigrationService.php
  lib/UserFolderExportDestination.php
Labels: 3. to review, bug

#79 Add API endpoints to start export and get export status
  appinfo/routes.php
  lib/Controller/ApiController.php
  lib/ExportDestination.php
  lib/Service/UserMigrationService.php
Labels: 3. to review

#91 Remove background job from info.xml to avoid empty job
  appinfo/info.xml
Labels: 3. to review

#92 Add notifier to make notifications work when export fails or succeed
  lib/AppInfo/Application.php
  lib/BackgroundJob/UserExportJob.php
  lib/Notification/Notifier.php
Labels: 4. to release

#98 Add import background job
  lib/BackgroundJob/UserImportJob.php
  lib/Db/UserImport.php
  lib/Db/UserImportMapper.php
  lib/Migration/Version00001Date20220412116131.php
  lib/Notification/Notifier.php
Labels: 3. to review, enhancement

#97 Complete User migration settings UI
  js/user_migration-admin-settings.js
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Migrator/FilesMigrator.php
  lib/Settings/Admin/Section.php
  lib/Settings/Personal/Section.php
  lib/Settings/Personal/Settings.php
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/personal-settings.js
  src/shared/constants.js
  src/views/Admin/Settings.vue
  src/views/Personal/Settings.vue
Labels: 3. to review, enhancement

#84 Preserve mtime
  lib/ExportDestination.php
  lib/ImportSource.php
  tests/psalm-baseline.xml
Labels: 4. to release

#102 Touch exported file after export
  lib/UserFolderExportDestination.php
Labels: 3. to review, bug

#103 Use exceptions instead of booleans
  lib/ExportDestination.php
  lib/ImportSource.php
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
Labels: 3. to review

#104 Fetch status before opening modal
  js/user_migration-admin-settings.js
  js/user_migration-admin-settings.js.LICENSE.txt
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.LICENSE.txt
  js/user_migration-personal-settings.js.map
  src/admin-settings.js
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/logger.js
  src/personal-settings.js
  src/shared/constants.js
  src/views/Admin/Settings.vue
  src/views/Personal/Settings.vue
Labels: 3. to review, bug

#105 Enable checkboxes by default and improve UX
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/views/Personal/Settings.vue
Labels: 3. to review, enhancement

#107 Add node workflow
  .github/workflows/node.yml
Labels: 3. to review

#108 Harden error handling to make sure no errors go unnoticed
  lib/ExportDestination.php
  lib/ImportSource.php
Labels: 3. to review

#106 Import API and UI
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/BackgroundJob/UserImportJob.php
  lib/Command/Import.php
  lib/Controller/ApiController.php
  lib/Db/UserImport.php
  lib/Db/UserImportMapper.php
  lib/Migration/Version00001Date20220412116131.php
  lib/Notification/Notifier.php
  lib/Service/UserMigrationService.php
  lib/UserFolderImportSource.php
  package-lock.json
  package.json
  src/components/ImportSection.vue
Labels: 3. to review, enhancement

#113 Call fclose on resource after export
  lib/UserFolderExportDestination.php
Labels: 3. to review

#114 Bump version number to 1.0.0
  appinfo/info.xml
Labels: 3. to review

#117 Sort originally unordered checkboxes
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  src/components/ExportSection.vue
Labels: 3. to review

#118 Release 1.0.1-beta1
  appinfo/info.xml
Labels: 4. to release

#109 File picker filter by export extension
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  src/components/ImportSection.vue
Labels: 3. to review

#119 Release 1.0.1-beta.2
  appinfo/info.xml
Labels: 3. to review

#122 Disable button while starting the export or import
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  src/components/ExportSection.vue
  src/components/ImportSection.vue
Labels: 4. to release, bug

#124 Update naming
  README.md
  appinfo/info.xml
Labels: 3. to review, backport-request

#127 Use main branch in workflows
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
Labels: 3. to review, backport-request

#132 Add eslint and stylelint workflows
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
Labels: 3. to review, backport-request

#123 Add API endpoint to cancel a job
  appinfo/routes.php
  js/user_migration-admin-settings.js.map
  js/user_migration-personal-settings.js
  js/user_migration-personal-settings.js.map
  lib/Controller/ApiController.php
  lib/Service/UserMigrationService.php
  package-lock.json
  package.json
  src/components/ExportSection.vue
  src/components/ImportSection.vue
  src/services/migrationService.js
  src/shared/constants.js
  src/views/Personal/Settings.vue
Labels: 3. to review, enhancement
