Repository nextcloud/user_migration, pull requests merged in 2023-02, with the labels that each got.

#333 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#340 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#353 Fix type error in debug mode when an Exception is thrown
  lib/Command/Export.php
Labels: 3. to review

#354 Apply node filter for comments and tags as well
  lib/Migrator/FilesMigrator.php
Labels: 3. to review, bug

#364 Improve verbose output when an exception happens
  lib/Command/Export.php
  lib/Command/Import.php
Labels: 4. to release

#291 Bump dev version on main
  appinfo/info.xml
Labels: 4. to release
