Repository nextcloud/user_migration, pull requests merged in 2023-05, with the labels that each got.

#402 feat(cli)!: Export to final destination directly
  lib/Command/Export.php
  lib/Command/Import.php
  lib/TempExportDestination.php
Labels: 3. to review

#403 Bump major dev version
  appinfo/info.xml
Labels: 3. to review

#405 Fix update-nextcloud-ocp to branch being named main and not master
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#406 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Migrator/FilesMigrator.php
Labels: 4. to release, dependencies

#412 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#413 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#411 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#417 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#408 feat: 32-bit support
  composer.lock
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
Labels: 4. to release, enhancement

#423 feat(deps): Add Nextcloud 28 support on main
  appinfo/info.xml
Labels: 4. to release

#422 chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
Labels: 4. to release

#429 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#428 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#434 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 4. to release, dependencies, automated

#433 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies
