Repository nextcloud/user_migration, pull requests merged in 2024-12, with the labels that each got.

#801 chore(deps): composer require --dev nextcloud/ocp:dev-master -W
  composer.lock
  lib/Db/UserExport.php
  lib/Db/UserImport.php
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 4. to release, dependencies

#804 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#803 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#806 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#810 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#811 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
