Repository nextcloud/user_migration, pull requests merged in 2024-03, with the labels that each got.

#619 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#624 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#625 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#626 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#628 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#633 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#632 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#608 fix: Avoid crashes in Notifier when user or file is not found
  lib/Notification/Notifier.php
Labels: 3. to review

#637 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#643 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
