Repository nextcloud/user_migration, pull requests merged in 2024-01, with the labels that each got.

#564 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#565 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#566 chore: update workflows from templates
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#567 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#574 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#573 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#572 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#578 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#579 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#580 Update npm and node engines versions
  package.json
Labels: dependencies

#585 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#584 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#586 Add update-nextcloud-ocp-approve-merge workflow from upstream
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#592 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#250 Add unit tests
  .gitignore
  composer.json
  phpunit.integration.xml
  phpunit.xml
  tests/Unit/ExampleTest.php
  tests/Unit/FilesMigratorTest.php
  tests/phpunit.integration.xml
  tests/phpunit.xml
Labels: 3. to review
