Repository nextcloud/user_migration, pull requests merged in 2024-09, with the labels that each got.

#746 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#747 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#748 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#749 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#750 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#759 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#758 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#762 chore: move tools to vendor bin plugin
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/BackgroundJob/UserExportJob.php
  lib/BackgroundJob/UserImportJob.php
  lib/Command/Export.php
  lib/Controller/ApiController.php
  lib/ExportDestination.php
  lib/ImportSource.php
  lib/Migrator/FilesMigrator.php
  lib/Service/UserMigrationService.php
  lib/Settings/Personal/Section.php
  lib/Settings/Personal/Settings.php
  tests/Unit/FilesMigratorTest.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#767 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#769 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#768 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#772 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#771 chore: Move into migration settings section
  lib/Settings/Personal/Section.php
  lib/Settings/Personal/Settings.php
Labels: 3. to review
