Repository nextcloud/user_migration, pull requests merged in 2025-05, with the labels that each got.

#866 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#869 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#873 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#872 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#879 Upgrade psalm to version 6
  REUSE.toml
  psalm.xml
  tests/psalm-baseline.xml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#880 chore(phpunit): Move phpunit to vendor-bin, update version
  .github/dependabot.yml
  .gitignore
  .nextcloudignore
  REUSE.toml
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3. to review

#863 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#882 chore(dependabot): Watch stable31 as well
  .github/dependabot.yml
Labels: 3. to review

#899 fix(cli): Abort early if file does not exist
  lib/Command/Import.php
Labels: 3. to review, backport-request
